version: "3.8"
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-WAF
    command: -l trace --concurrency 1 -c /etc/envoy.yaml
    entrypoint: /usr/local/bin/envoy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
      - ./WAF_wasm.wasm:/etc/WAF_wasm.wasm
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - WAF-integration-test
networks:
  WAF-integration-test: {}

