version: "3.8"
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-WAF
    command: -l error --concurrency 1 -c /etc/envoy.yaml
    entrypoint: /usr/local/bin/envoy
    volumes:
      - ./envoy-test.yaml:/etc/envoy.yaml
      - ../WAF_wasm.wasm:/etc/WAF_wasm.wasm
    ports:
      - "8000:8000"
    networks:
      - WAF-integration-test
  client-server:
    build:
      context: .
      dockerfile: Dockerfile-client-server
    ports:
      - "8080:8080"
    networks:
      - WAF-integration-test
networks:
  WAF-integration-test: {}

